-- =============================================
-- ⚠️ DEPRECATED — DO NOT USE
-- =============================================
-- This file used to disable RLS on all tables.
-- That was a security risk.
--
-- USE INSTEAD: supabase-rls-fix.sql
-- That file creates proper per-user RLS policies.
--
-- If you already ran this file and want to fix it:
-- 1. Run supabase-rls-fix.sql to create proper policies
-- 2. Then re-enable RLS on any table you disabled:
--
-- ALTER TABLE company_profiles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE saved_investors ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE email_messages ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE email_accounts ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE campaigns ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE saved_filters ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE audit_log ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE acquisition_jobs ENABLE ROW LEVEL SECURITY;

SELECT 'DEPRECATED: Use supabase-rls-fix.sql instead. This file disables RLS which is a security risk.' as warning;
